# These are supported funding model platforms
github: #[heavenya]
webste & venmo: # Replace with up to 4 custom sponsorship URLs e.g., ['https://venmo.com/u/heavenya', 'https://heavenya.com/?form=donate', 'https://github.com/sponsors/heavenya']
